<?php
    $this->jQuery();
    $this->bootstrap('js/bootstrap.min.js');
?>
<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Private message'); ?>"><?php _e('Private message'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>" title="<?php _e('Notification'); ?>"><?php _e('Notification'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?>" title="<?php _e('Send message'); ?>"><?php _e('Send message'); ?></a></li>
</ul>

<?php
    if (!empty($errMessage)) {
        $class = ' alert-error';
?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $errMessage; ?>
</div>

<?php } ?>

<?php
    $form->setAttribute('class', 'form-horizontal');
    echo $this->form()->openTag($form);
    $this->FormElementErrors()->setMessageOpenFormat('<span class="help-inline">')->setMessageCloseString('</span>');
?>
<legend><?php echo $this->escape($title); ?></legend>
<?php
    $element = $form->get('username');
    echo sprintf('<div class="control-group%s"><label class="control-label">%s</label><div class="controls">%s%s</div></div>',
    $element->getMessages() ? ' error' : '',
    $element->getOption('label'),
    $this->formElement($element),
    $this->formElementErrors($element));
?>
<?php
    $element = $form->get('content');
    $element->setAttributes(array(
            'class' => 'span7',
            'rows' => '6'
    ));
    echo sprintf('<div class="control-group%s"><label class="control-label">%s</label><div class="controls">%s%s</div></div>',
    $element->getMessages() ? ' error' : '',
    $element->getOption('label'),
    $this->formElement($element),
    $this->formElementErrors($element));
?>
<?php
    $element = $form->get('submit');
    $element->setAttribute('class', 'btn btn-primary');
    echo sprintf('<div class="controls">%s</div>', $this->formSubmit($element));
    echo $this->form()->closeTag($form); 
?>