<?php $this->css($this->assetModule('script/front.css')); ?>
    <div class="clearfix row user-section-wrapper">
        <div class="col-md-3">
            <?php $sideActive = 'message'; ?>
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <?php include $this->template('flash-messenger'); ?>
            <ul class="nav nav-tabs message-nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" href="<?php echo $this->url('', ['controller' => 'index', 'action' => 'index']); ?>"
                       title="<?php _e('Private message'); ?>"><?php echo $messageTitle; ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->url('', ['controller' => 'notify', 'action' => 'index']); ?>"
                       title="<?php _e('Notification'); ?>"><?php echo $notificationTitle; ?></a>
                </li>
            </ul>
            <?php if (!empty($errMessage)) {
                $class = ' alert-error'; ?>
                <div class="alert<?php echo $class; ?>">
                    <?php echo $errMessage; ?>
                </div>
            <?php } ?>
            <?php if (!empty($list)) { ?>
                <?php foreach ($list as $singleMessage) { ?>
                    <div class="messages" id="message-js">
                    <div class="media message-detail">
                        <div class="message-detail-head">
                            <h4 class="media-heading float-left message-head">
                                <span><?php echo $uid == $singleMessage['uid_from'] ? __('To') : __('From'); ?></span>
                                <a href="<?php echo $singleMessage['profileUrl']; ?>"><?php echo $singleMessage['name']; ?></a>
                            </h4>
                            <p class="message-time text-right mb-2">
                                <span class="muted"><?php echo _date($singleMessage['time_send']); ?></span>
                            </p>
                        </div>
                        <div class="media message-detail-primary mt-3 d-flex">
                            <a href="<?php echo $singleMessage['profileUrl']; ?>" class="float-left">
                                <?php echo $singleMessage['avatar']; ?>
                            </a>
                            <div class="media-body message-detail-con">
                                <p><?php echo $singleMessage['content']; ?></p>
                                <div class="message-detail-hidden">
                                    <p class="float-right mb-2">
                                        <a href="<?php echo $this->url(
                                            '', ['action' => 'delete', 'ids' => $singleMessage['id'], 'tid' => $singleMessage['uid_to']]
                                        ); ?>"
                                           class="js-delete">
                                            <?php _e('Delete'); ?>
                                        </a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="clearfix card bg-light mb-3">
                    <?php echo $this->form($form, 'horizontal'); ?>
                </div>
                </div>
            <?php } else { ?>
                <p class>
                    <br>
                    <?php _e('This conversation is no longer available') ?>
                </p>
            <?php } ?>
            <?php include $this->template('./_confirm-modal.phtml'); ?>
        </div>
    </div>
<?php
$paginator = isset($paginator) ? $paginator->getCurrentPageNumber() : '';
$host      = $this->url('', ['module' => 'message']);
$confirm   = addslashes(__('Once you delete this message, it cannot be undone.'));
$script    = "messageIndex({p: '%s', host: '%s', confirm: '%s'});";
$script    = sprintf($script, $paginator, $host, $confirm);

$this->footScript()->appendFile($this->assetModule('script/index-detail.js'));
$this->footScript()->appendScript($script);
?>
