<?php $this->css($this->assetModule('script/front.css')); ?>
    <div class="clearfix">
        <div class="col-md-3">
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h1><?php _e('Message'); ?></h1>
            </div>
            <ul class="nav nav-tabs message-nav-tabs">
                <li class="active">
                    <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>"
                       title="<?php _e('Private message'); ?>"><?php echo $messageTitle; ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'archive')); ?>"
                       title="<?php _e('Archive'); ?>"><?php _e('Archive'); ?></a>
                </li>
                <!--    <li>-->
                <!--        <a href="-->
                <?php //echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?><!--" title="-->
                <?php //_e('Notification'); ?><!--">--><?php //echo $notificationTitle; ?><!--</a>-->
                <!--    </li>-->
                <!--    <li>-->
                <!--        <button type="button" class="btn message-nav-btn" onclick="location.href=-->
                <!--        '-->
                <?php //echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?><!--'" -->
                <!--        title="--><?php //_e('New message'); ?><!--">--><?php //_e('New message'); ?>
                <!--        </button>-->
                <!--    </li>-->
            </ul>
            <div class="messages" id="message-js">
                <?php if (!empty($messages)) { ?>
                    <?php foreach ($messages as $message) { ?>
                        <div class="clearfix message-item<?php if ($message['is_read_to']) { echo ' bg-warning'; } ?>">
                            <div class="col-md-2">
                                <div class='message-media-left clearfix'>
                                    <input type="checkbox" class="message-js-check pull-left"
                                           data-id="<?php echo $message['id']; ?>">
                                    <a href="<?php echo $message['profileUrl']; ?>" class="pull-left">
                                        <?php echo $message['avatar']; ?>
                                    </a>
                                </div>
                                <div class="clearfix">
                                    <br />
                                    <span class="muted">
                                        <?php echo $uid == $message['uid_from'] ? __('To') : __('From'); ?>
                                    </span>
                                    <a href="<?php echo $message['profileUrl']; ?>" class="message-user-name">
                                        <?php echo $message['name']; ?>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="message-content">
                                    <a href="<?php echo $this->url('', array('action' => 'detail', 'mid' => $message['id'])); ?>"
                                       class="message-content-link"><?php echo $message['content']; ?>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="pull-right text-right">
                                    <p class="message-time muted">
                                        <?php echo _date($message['time_send']); ?>
                                    </p>
                                    <p class="message-hidden"></p>
                                    <ul class="list-inline">
                                        <li>
                                            <a href="<?php if (isset($paginator)) {
                                                echo $this->url('', array(
                                                    'action' => 'delete',
                                                    'ids' => $message['id'],
                                                    'p' => $paginator->getCurrentPageNumber()
                                                ));
                                            } else {
                                                echo $this->url('', array('action' => 'delete', 'ids' => $message['id']));
                                            } ?>" class="message-js-delete"
                                               data-confirm="<?php _e('Once you delete this message, it cannot be undone.'); ?>">
                                                <?php _e('Delete'); ?>
                                            </a>
                                        </li>
                                        <li class="message-divider">|</li>
                                        <li class="message-mark">
                                            <a href="<?php if (isset($paginator)) {
                                                echo $this->url('', array(
                                                    'action' => 'mark',
                                                    'ids' => $message['id'],
                                                    'p' => $paginator->getCurrentPageNumber()
                                                ));
                                            } else {
                                                echo $this->url('', array('action' => 'mark', 'ids' => $message['id']));
                                            } ?>">
                                                <?php _e('Mark as read'); ?>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                <?php } else {
                    _e('<div class="alert alert-info message-alert">No message for you!</div>');
                } ?>
                <?php
                if (isset($paginator)) {
                    echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array(
                        'class' => 'pagination-right pull-right message-pagination'
                    ));
                }
                ?>
                <form class="form-inline pull-left message-foot-form" action="">
                    <input type="checkbox" class="message-js-batch" title="<?php _e('Checked all'); ?>">
                    <select class="message-batch-action">
                        <option value=""><?php _e('Massive operation'); ?></option>
                        <option value="mark"><?php _e('Mark as read'); ?></option>
                        <option value="delete"><?php _e('Delete'); ?></option>
                    </select>
                </form>
            </div>
        </div>
    </div>
<?php
$paginator = isset($paginator) ? $paginator->getCurrentPageNumber() : '';
$host = $this->url('', array('module' => 'message'));
$confirm = __('Once you delete those message, it cannot be undone.');
$script = "messageIndex({p: '%s', host: '%s', confirm: '%s'});";
$script = sprintf($script, $paginator, $host, $confirm);

$this->footScript()->appendFile($this->assetModule('script/index-index.js'));
$this->footScript()->appendScript($script);
?>