<?php
    $this->css($this->assetModule('script/front.css'));
    $this->jQuery();
    $this->bootstrap('js/bootstrap.min.js');
?>
<ul class="nav nav-tabs">
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Private message'); ?>"><?php _e('Private message'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>" title="<?php _e('Notification'); ?>"><?php _e('Notification'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?>" title="<?php _e('Send message'); ?>"><?php _e('Send message'); ?></a></li>
</ul>

<?php
    if (!empty($errMessage)) {
        $class = ' alert-error';
?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $errMessage; ?>
</div>

<?php }
if (!empty($message)) { ?>
<div class="messages" id="message-js">
    <div class="row-fluid message-item">
        <div class="span1">
            <?php echo $message['avatar']; ?>
        </div>
        <div class="span9">
            <div class="message-head">
                <strong class="message-title"><?php echo $message['username'] . ':'; ?></strong>
            </div>
            <pre class="message-body"><?php echo $this->escape($message['content']); ?></pre>
            <small class="message-action">
                <a href="<?php echo $this->url('', array('action' => 'delete', 'ids' => $message['id'], 'tid' => $message['uid_to'])); ?>"><?php _e('Delete'); ?></a>
            </small>
        </div>
        <div class="span2">
            <span class="muted"><?php echo date('Y/m/d H:i', $message['time_send']); ?></span>
        </div>
    </div>
    <div class="row-fluid message-item">
        <div class="span1">
            <?php echo $myAvatar; ?>
        </div>
        <div class="span11">
            <?php echo $this->form()->openTag($form); ?>
            <?php 
                $element = $form->get('content');
                $element->setAttributes(array(
                    'class' => 'span7',
                    'rows' => '6'
                ));
                echo '<div class="message-send-text">' . $this->formElement($element);
                echo $this->formElementErrors($element);
                echo '</div>'
            ?>
            <?php
                echo $this->formElement($form->get('uid_to'));
                $element = $form->get('submit');
                $element->setAttributes(array(
                    'class' => 'btn btn-primary',
                ));
                echo $this->formSubmit($element); 
                echo $this->form()->closeTag($form); 
            ?>
        </div>
    </div>
</div>
<?php } ?>