<?php
    $this->css($this->assetModule('script/front.css'));
    $this->jQuery();
?>
<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Private message'); ?>"><?php _e('Private message'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>" title="<?php _e('Notification'); ?>"><?php _e('Notification'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?>" title="<?php _e('Send message'); ?>"><?php _e('Send message'); ?></a></li>
</ul>
<div class="messages" id="message-js">
    <?php if (!empty($notifications)) { ?>
    <form class="form-inline" method="post" action="">
        <input type="checkbox" class="message-js-batch" title="<?php _e('Checked all'); ?>">
        <select class="message-batch-action">
            <option value=""><?php _e('With selected:'); ?></option>
            <option value="delete"><?php _e('Delete'); ?></option>
            <option value="mark"><?php _e('Mark read'); ?></option>
        </select>
    </form>
    <?php foreach ($notifications as $notification) { ?>
    <div class="row-fluid message-item<?php if($notification['is_new']) { echo ' message-item-read'; } ?>">
        <div class="span1">
            <?php echo $adminAvatar; ?>
        </div>
        <div class="span9">
            <div class="message-head">
                <input type="checkbox" class="message-js-check" data-id="<?php echo $notification['id']; ?>">
                <strong class="message-title"><?php echo $adminName ?></strong>
            </div>
            <p class="message-body"><?php echo _escape($notification['subject']); ?></p>
            <small class="message-action">
                <a href="
                <?php echo $this->url('', array('action' => 'detail', 'mid' => $notification['id'])); ?>">
                    <?php _e('Detail'); ?>
                </a>
                <span class="pi-divider">|</span>
                <a href="<?php
                    if (isset($paginator)) {
                        echo $this->url('', array(
                            'action' => 'delete',
                            'ids'    => $notification['id'],
                            'p'      => $paginator->getCurrentPageNumber()
                        ));
                    } else {
                        echo $this->url('', array('action' => 'delete', 'ids' => $notification['id']));
                    }
                ?>" class="message-js-delete">
                    <?php _e('Delete'); ?>
                </a>
            </small>
        </div>
        <div class="span2">
            <span class="muted"><?php echo date('Y/m/d H:i', $notification['time_send']); ?></span>
        </div>
    </div>
    <?php } ?>
    <?php } else {
        _e('No notification for you!');
    } ?>
    <?php
        if (isset($paginator)) {
            echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array(
                'class' => 'pagination-right'
            ));
        }
    ?>
</div>
<script src="<?php echo $this->assetModule('script/notify-index.js'); ?>"></script>
<script>
messageIndex({
    p: '<?php echo isset($paginator) ? $paginator->getCurrentPageNumber() : ''; ?>',
    host: '<?php echo $this->url('', array('module' => 'message')); ?>'
});
</script>