<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/front.css'));
    $this->jQuery();
?>

<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Private message'); ?>"><?php _e('Private message'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>" title="<?php _e('Notification'); ?>"><?php _e('Notification'); ?></a></li>
    <li><button type="button" class="btn message-nav-btn" onclick="location.href='<?php echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?>'" title="<?php _e('New message'); ?>"><?php _e('New message'); ?></button></li>
</ul>

<div class="messages" id="message-js">
    <?php if (!empty($notifications)) { ?>
    <?php foreach ($notifications as $notification) { ?>   
    <div class="media message-item<?php if($notification['is_new']) { echo ' message-item-read'; } ?>">
        <div class='pull-left'>
            <input type="checkbox" class="message-js-check" data-id="<?php echo $notification['id']; ?>">
        </div>
        <div class="pull-right text-right message-media-right">
            <p class="message-time">
                <span class="muted"><?php echo date('Y/m/d H:i', $notification['time_send']); ?></span>
            </p>
            <p class="message-hidden">
                <span>
                    <a href="<?php
                    if (isset($paginator)) {
                        echo $this->url('', array(
                            'action' => 'mark',
                            'ids'    => $notification['id'],
                            'p'      => $paginator->getCurrentPageNumber()
                        ));
                    } else {
                        echo $this->url('', array('action' => 'mark', 'ids' => $notification['id']));
                    }
                ?>">
                    <?php _e('Mark as read'); ?>
                    </a>
                </span>
                <span class="message-divider">|</span>
                <span>
                    <a href="<?php
                    if (isset($paginator)) {
                        echo $this->url('', array(
                            'action' => 'delete',
                            'ids'    => $notification['id'],
                            'p'      => $paginator->getCurrentPageNumber()
                        ));
                    } else {
                        echo $this->url('', array('action' => 'delete', 'ids' => $notification['id']));
                    }
                ?>" class="message-js-delete">
                    <?php _e('Delete'); ?>
                    </a>
                </span>
            </p>
        </div>
        <div class="media-body message-content">
            <h5 class="media-heading message-head">                
                <a href="#"><?php echo _escape($notification['subject']); ?></a>
                <span class="label label-info message-label-type">Type B</span>
            </h5>
            <p class="message-body">
                <a href="<?php echo $this->url('', array('action' => 'detail', 'mid' => $notification['id'])); ?>">
                    <?php echo $notification['content']; ?>
                </a>
            </p>
        </div>   
    </div>
        <?php } ?>
        <?php } else {
            _e('<div class="alert alert-info message-js-alert">No notification for you!</div>');
        } ?>
    <?php
        if (isset($paginator)) {
            echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array(
                'class' => 'pagination-right'
            ));
        }
    ?>
    <form class="form-inline message-foot-form" action="">
        <input type="checkbox" class="message-js-batch" title="<?php _e('Checked all'); ?>">
        <select class="message-batch-action">
            <option value=""><?php _e('Massive operation'); ?></option>
            <option value="mark" ><?php _e('Mark read'); ?></option>
            <option value="delete"><?php _e('Delete'); ?></option>
        </select>
    </form>
</div>

<script>    
    (function($) {
        $('.message-item').bind("click", function (c) {
            if (c.target.tagName === "A" || c.target.tagName === "INPUT"||c.target.tagName === "IMG") {
                return;
            }
            window.location= $(this).find(".message-content p a").attr("href")
        });
        $('.message-item-read').css('background','#eefbff');
        $('.message-item').not('.message-item-read').find('p.message-hidden>span>a:firstChild').empty();
        $('.message-item').not('.message-item-read').find('p.message-hidden>span.message-divider').empty();
        $('.message-item-read .message-content p>a').css('color','#333');
        $('.message-js-alert').next('form').remove();

        $('.message-js-delete').click(function() {
            if(!confirm('确定要删除')) {
                return false;
            }
        });

        $('.message-batch-action').change(function(event){
            if($(this).val() == 'delete'){
                if(!confirm('Are you sure to delete the message selected ?')) {
                    event.stopImmediatePropagation();
                }
            }  
        })
    })(jQuery)
</script>
<script src="<?php echo $this->assetModule('script/notify-index.js'); ?>"></script>
<script>
    messageIndex({
        p: '<?php echo isset($paginator) ? $paginator->getCurrentPageNumber() : ''; ?>',
        host: '<?php echo $this->url('', array('module' => 'message')); ?>'
    });
</script>

