<?php
    $this->css($this->assetModule('script/front.css'));
    $this->jQuery();
    $this->bootstrap('js/bootstrap.min.js');
?>
<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Private message'); ?>"><?php _e('Private message'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>" title="<?php _e('Notification'); ?>"><?php _e('Notification'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?>" title="<?php _e('Send message'); ?>"><?php _e('Send message'); ?></a></li>
</ul>

<?php
    if (!empty($errMessage)) {
        $class = ' alert-error';
?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $errMessage; ?>
</div>

<script>$(".alert").alert();</script>
<?php }

if (!empty($notification)) { ?>
<div class="messages" id="message-js">
    <div class="row-fluid message-item">
        <div class="span1">
            <?php echo $notification['avatar']; ?>
        </div>
        <div class="span9">
            <div class="message-head">
                <strong class="message-title">
                    <?php echo $notification['username'] . ':'; ?>
                    <?php
                        echo '<br />';
                        if (!empty($notification['tag'])) {
                            echo '[' . $notification['tag']. '] ';
                        }
                        echo $notification['subject'];
                    ?>
                </strong>
            </div>
            <pre class="message-body"><?php echo $this->escape($notification['content']); ?></pre>
            <small class="message-action">
                <a href="<?php echo $this->url('', array('action' => 'delete', 'ids' => $notification['id'])); ?>"><?php _e('Delete'); ?></a>
            </small>
        </div>
        <div class="span2">
            <span class="muted"><?php echo date('Y/m/d H:i', $notification['time_send']); ?></span>
        </div>
    </div>
</div>
<?php } ?>