<?php $this->css($this->assetModule('script/front.css')); ?>
    <div class="clearfix row">
        <div class="col-md-3">
            <?php $sideActive = 'notification'; ?>
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <ul class="nav nav-tabs message-nav-tabs">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>"
                       title="<?php _e('Private message'); ?>"><?php echo $messageTitle; ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>"
                       title="<?php _e('Notification'); ?>"><?php echo $notificationTitle; ?></a>
                </li>
            </ul>
            <?php if (!empty($errMessage)) { ?>
                <div class="alert alert-error">
                    <button data-dismiss="alert" class="close" type="button">
                        ×
                    </button>
                    <?php echo $errMessage; ?>
                </div>
                <?php
                $script = "$('.alert').alert();";
                $this->footScript()->appendScript($script);
                ?>
            <?php } ?>
            <?php if (!empty($notificationDetail)) { ?>
                <div class="messages" id="message-js">
                    <div class="media message-detail">
                        <div class="message-detail-head">
                            <h4 class="media-heading pull-left message-head">
                                <?php echo $notificationDetail['subject'] ?>
                                <?php if (!empty($notificationDetail['tag'])) { ?>
                                    <span class="badge badge-info message-label-type">
                                    <?php echo $notificationDetail['tag']; ?>
                                    </span>
                                <?php } ?>
                            </h4>
                            <p class="message-time text-right">
                            <span class="muted">
                                <?php echo _date($notificationDetail['time_send']); ?>
                            </span>
                            </p>
                        </div>
                        <div class="media message-detail-primary">
                            <div class="media-body">
                                <p class="message-body"><?php echo $notificationDetail['content']; ?></p>
                                <p class="pull-right">
                                    <a href="<?php echo $this->url('', array('action' => 'delete', 'ids' => $notification['id'])); ?>"
                                       data-confirm="<?php _e('Once you delete this message, it cannot be undone.'); ?>">
                                        <?php _e('Delete'); ?>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <?php include $this->template('./_confirm-modal.phtml'); ?>
        </div>
    </div>
<?php
$paginator = isset($paginator) ? $paginator->getCurrentPageNumber() : '';
$host = $this->url('', array('module' => 'message'));
$script = "messageIndex({p: '%s', host: '%s'});";
$script = sprintf($script, $paginator, $host);

$this->footScript()->appendFile($this->assetModule('script/notify-index.js'));
$this->footScript()->appendScript($script);
?>